### ISSUE TITLE
Missing binding eigenpy 

### ISSUE THREAD

**Issue by longhathuc** [stack-of-tasks/sot-tiago#11]
In the file /opt/openrobots/lib/python2.7/site-packages/dynamic_graph/sot/tiago/steel/prologue.py
Missing  binding eigenpy leads to the failure reading tiagostell urdf bounds values
```
import eigenpy
eigenpy.switchToNumpyMatrix()

```

**Comment by jmirabel** [comment]
The patch that was applied to sot-talos should be applied here too: https://github.com/Gepetto/robotpkg-wip/blob/master/py-sot-talos/patches/patch-aa

See with @nim65s for some guidance.

**Comment by nim65s** [comment]
We totally do, thanks.

@longhathuc : I think you are the only one impacted with this for now. Is this blocking for you, or can you setup a temporary workaround, and show me more precisely this on your computer on Monday ?

**Comment by longhathuc** [comment]
It's ok, I have patched manually in the robots

**Comment by jmirabel** [comment]
Fixed by #13
