### ISSUE TITLE
Gazebo Crash when loading Tiago Sot controller with wheel configuration

### ISSUE THREAD

**Issue by longhathuc** [stack-of-tasks/sot-tiago#8]
When using the Tiago Sot controller with wheel configuration in the file "sot_tiago_params_gazebo_with_mobile_base.yaml", gazebo crashed

- Possible error due to the same behavior of the files libsot-tiago-steel-controller.so and libsot-tiago-without-wheels-controller.so, which both do not accept the wheels' parameters.
-  When loading with wheel configuration or not, the robot with be created with the constructor (with_wheels = False) `robot = dynamic_graph.sot.tiago.steel.prologue.makeRobot (with_wheels=False)`

**Comment by jmirabel** [comment]
This issue will be solved by:
- https://github.com/stack-of-tasks/tiago_metapkg_ros_control_sot/pull/6
- https://github.com/stack-of-tasks/tiago_data/pull/6
- https://github.com/stack-of-tasks/sot-tiago/pull/9

As a bonus, https://github.com/stack-of-tasks/roscontrol_sot/pull/17 gives a better error message.

**Comment by jmirabel** [comment]
Fixed by #13
